### PR TITLE
Create a register page (#3)

### PR DESCRIPTION
**Pull request by nicolafan**
Create layout for register page (activity_register.xml) and connect layout to Activity.

Navigation from login to register page and backwards.

### CODE REVIEW

**Comment by nicolafan** [comment]
Schermata da 2021-10-02 15-09-17

**Comment by Mustafa2856** [comment]
@nicolafan  It Looks good,
For going back to sign-up page can you use `finish()` to close current register page instead of creating another instance of the login activity

**Comment by Mustafa2856** [comment]
Works properly

**Comment by nicolafan** [comment]
@Mustafa2856 `FLAG_ACTIVITY_CLEAR_TOP` avoids creating a new instance but btw you're right. This solution is probably better, I did it.

**Pull request merged**
